### ISSUE TITLE
2017 Mar 28: faustplayground site fails with Error: Unable to access URL .../math.lib

### ISSUE THREAD

**Issue by sdaau** [grame-cncm/faustplayground#2]
I try opening: http://grame-cncm.github.io/faustplayground/
* Then I click on Load
* Then I click on "small example"
* I get a "Loading" splash screen
* Finally, I get an error "Error: Unable to access URL 'http://grame-cncm.github.io/faustplayground/faustcode/math.lib'" - and clearly, nothing loads/works

![screenshot-faustplayground](https://cloud.githubusercontent.com/assets/26737749/24399682/d042241a-13ad-11e7-9e21-56a06c6cc426.png)

Same problem with trying to paste code that uses `math.lib`.

This is weird, because I can see `math.lib` in the code:
https://github.com/grame-cncm/faustplayground/tree/master/faustcode

... however, the link http://grame-cncm.github.io/faustplayground/faustcode/math.lib does indeed 404.

Can you try fixing this?

**Comment by sletz** [comment]
Known problem, that we'll fix at next update of the platform.

**Comment by sletz** [comment]
Fixed.
