### ISSUE TITLE
Removing the faustlibraries folder

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faustplayground#6]
Faust libraries are now embedded in https://github.com/grame-cncm/faustplayground/blob/master/libfaust-wasm.data. So AFAICS the `faustlibraries` folder can now be removed. Anything I've missed ? OK for you @dfober, @orlarey and @rmichon ?

**Comment by rmichon** [comment]
I guess that's OK to remove it then, indeed...

**Comment by dfober** [comment]
this should not be a problem, provided it's using the new version of the
library
(don't know for the previous version)

Le ven. 30 avr. 2021 à 15:31, Stéphane Letz ***@***.***> a
écrit :
